# Site settings
title: toice's blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://toice.net" # the base hostname & protocol for your site

# Build settings

# Conversion
markdown: kramdown
highlighter: pygments

# Plugins
gems: 
- jekyll-compass
output_style: compressed
line_comments: false

# Outputting
permalink: /:categories/:title
paginate: 5
paginate_path: /page:num
timezone:      Asia/Seoul